version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: aleksandr
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bankAccount
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8888:8888"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}